apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: house-price-pipeline
  labels:
    scenarios.ai.sap.com/id: house-price-prediction-scenario
    ai.sap.com/version: "1.0"
spec:
  entrypoint: run
  templates:
    - name: run
      steps:
        - - name: predictor
            template: predictor-task

    - name: predictor-task
      container:
        image: docker.io/muthurammurugan/house-price:03
        command: [ "python", "/app/src/main.py" ]
