apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: house-server-pipeline
  annotations:
    scenarios.ai.sap.com/name: "House Price Prediction"
    scenarios.ai.sap.com/description: "Server to predict house prices"
    executables.ai.sap.com/name: "server"
    executables.ai.sap.com/description: "Flask server for online inference"
    artifacts.ai.sap.com/housepricemodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: house-price
    ai.sap.com/version: "1.0"
spec:
  inputs:
    artifacts:
      - name: housepricemodel
    parameters:
      - name: greetmessage
        type: string
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: credstutorialrepo
        minReplicas: 1
        maxReplicas: 2
        containers:
          - name: kserve-container
            image: "docker.io/muthurammurugan/house-server:01"
            ports:
              - containerPort: 9001
            command: ["/bin/sh", "-c"]
            args:
              - >
                set -e &&
                echo "Starting" &&
                gunicorn --chdir /app/src main:app -b 0.0.0.0:9001
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.housepricemodel}}"
              - name: greetingmessage
                value: "{{inputs.parameters.greetmessage}}"
